export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const USER_ON_VALIDATE_REQUESTED = 'USER_ON_VALIDATE_REQUESTED';
export const USER_ON_VALIDATE_SUCCEEDED = 'USER_ON_VALIDATE_SUCCEEDED';
export const USER_ON_VALIDATE_FAILED = 'USER_ON_VALIDATE_FAILED';

export const USER_ON_GET_2FA_REQUESTED = 'USER_ON_GET_2FA_REQUESTED';
export const USER_ON_GET_2FA_SUCCEEDED = 'USER_ON_GET_2FA_SUCCEEDED';
export const USER_ON_GET_2FA_FAILED = 'USER_ON_GET_2FA_FAILED';
